name: Daily Cars & Bids Scraper

on:
  schedule:
    - cron: "0 12 * * *"   # every day at 12:00 UTC
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cab-daily-scraper   # all steps run inside this folder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer axios

      - name: Run scraper
        run: node scraper.js
