name: Daily Cars & Bids Scraper

on:
  schedule:
    - cron: "0 12 * * *"   # every day at 12:00 UTC
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cab-daily-scraper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node scraper.js

      - name: Upload results (keep daily files)
        uses: actions/upload-artifact@v4
        with:
          name: carsandbids-${{ github.run_id }}
          path: cab-daily-scraper/output/
